samples:
  sample1: sample_data/raw_reads/sample1.fastq.gz
  sample2: sample_data/raw_reads/sample2.fastq.gz
  sample3: sample_data/raw_reads/sample3.fastq.gz

genome: sample_data/amplicon.fa

adapters: "/home/buyar/tools/QC/Trimmomatic-0.33/adapters/adaptors_list.all.fa"

nodeN: 4
