(specifications->manifest
 (list "python"
       "python-graphviz"
       "python-pyyaml"
       "python-pandas"

       "samtools"
       "snakemake"
       "bbmap"
       "trim-galore"
       "fastqc"
       "bedops"
       "multiqc"

       "r-minimal"
       "r-biostrings"
       "r-data-table"
       "r-dt"
       "r-fastseg"
       "r-genomeinfodb"
       "r-genomicalignments"
       "r-genomicranges"
       "r-ggplot2"
       "r-ggpubr"
       "r-ggrepel"
       "r-gtools"
       "r-iranges"
       "r-knitr"
       "r-pbapply"
       "r-pheatmap"
       "r-plotly"
       "r-reshape2"
       "r-rmarkdown"
       "r-rsamtools"
       "r-rtracklayer"
       "r-yaml"))
